version: "3.5"

services:
  apisix-dashboard:
    image: apache/apisix-dashboard:2.6
    restart: always
    volumes:
    - ./apisix/dashboard_conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    ports:
    # - "9000:9000"
    - "9001:9000"
  apisix:
    image: apache/apisix:2.6-alpine
    restart: always
    volumes:
      - ./apisix/apisix_log:/usr/local/apisix/logs
      - ./apisix/apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ports:
      # - "9080:9080/tcp"
      # - "9443:9443/tcp"
      - "9081:9080/tcp"
  etcd:
    image: bitnami/etcd:3.4.15
    user: root
    restart: always
    volumes:
      - ./etcd/etcd_data:/bitnami/etcd
    environment:
      - ETCD_DATA_DIR=/bitnami/etcd
      - ETCD_ENABLE_V2=true
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    ports:
      - "2379:2379/tcp"
  nacos:
    image: nacos/nacos-server:2.0.0 
    env_file:
      - ./nacos/env/nacos-standlone-mysql.env
    volumes:
      - ./nacos/logs/:/home/nacos/logs
      - ./nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9555:9555"
    depends_on:
      - mysql
    restart: always
  mysql:
    image: nacos/nacos-mysql:5.7
    env_file:
      - ./nacos/env/mysql.env
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus-standalone.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - nacos
    restart: always
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    restart: always
  postgres:
    image: postgres:10.7
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: wolf
    volumes:
      - ./wolf-rbac/server/script/db.sql:/docker-entrypoint-initdb.d/db.sql:ro
  wolf-server:
    image: igeeky/wolf-server
    restart: always
    ports:
      - "10080:10080"
    depends_on:
      - postgres
    environment:
      RBAC_ROOT_PASSWORD: wolf-123456
      RBAC_TOKEN_KEY: f40215a5f25cbb6d36df07629aaf1172240fe48d
      WOLF_CRYPT_KEY: fbd4962351924792cb5e5b131435cd30b24e3570
      RBAC_SQL_URL:  postgres://root:123456@postgres:5432/wolf
      CLIENT_CHANGE_PWD: "no"
    command: npm run start
  wolf-agent-or:
    image: igeeky/wolf-agent
    restart: always
    ports:
     - "10082:10082"
    depends_on:
      - wolf-server
    environment:
      BACKEND_URL: http://openresty.org
      RBAC_SERVER_URL: http://wolf-server:10080
      RBAC_APP_ID: openresty  
networks:
  default:
    external:
      name: aixichen-center-net
